### Version Check

In [1]:
import tensorflow as tf
print("Tensorflow Version: {}".format(tf.__version__))
print("Keras Version: {}".format(tf.keras.__version__))

Tensorflow Version: 2.0.0
Keras Version: 2.2.4-tf


Eager Execution is by default in Tensorflow 2.0 and, it need no special setup. The Following below code used to find out whether a CPU or GPU is in use.

### GPU/CPU Check

In [2]:
variable  = tf.Variable([3,3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('CPU')

CPU


### Tensor Constant

In [3]:
var1 = tf.constant(42)
var1

<tf.Tensor: id=8, shape=(), dtype=int32, numpy=42>

In [4]:
var2 = tf.constant([[3,3], [9,5]])
var2

<tf.Tensor: id=9, shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [9, 5]])>

In [5]:
var3 = tf.constant(1, dtype = 'int64')
var3

<tf.Tensor: id=10, shape=(), dtype=int64, numpy=1>

In [6]:
var4 = tf.constant([[4,5], [6,7]], dtype = 'int64')
var4

<tf.Tensor: id=11, shape=(2, 2), dtype=int64, numpy=
array([[4, 5],
       [6, 7]], dtype=int64)>

In [7]:
print('shape: ', var4.shape)
print(var4.dtype)

shape:  (2, 2)
<dtype: 'int64'>


#### Commonly used method is to generate constant tf.ones and tf.zeros like of numpy np.ones and np.zeros

In [8]:
print(tf.ones(shape = (2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [9]:
print(tf.zeros(shape = (3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [10]:
print(tf.ones)

<function ones at 0x000001AEFFFCF268>


In [11]:
print(tf.zeros)

<function zeros at 0x000001AEFFFCBBF8>


In [12]:
import tensorflow as tf
cons1 = tf.constant([[2,4,6], [5,6,8]])
cons2 = tf.constant([[1,4,6], [3,7,9]])
final_cons = tf.add(cons1,cons2)
final_cons

<tf.Tensor: id=20, shape=(2, 3), dtype=int32, numpy=
array([[ 3,  8, 12],
       [ 8, 13, 17]])>

We have defined two constant and we add one value to other. As a result we got a tensor object with the final_cons of adding.

### Random Constant

In [13]:
tf.random.normal(shape = (2,3), mean=0.0, stddev=1.0)

<tf.Tensor: id=26, shape=(2, 3), dtype=float32, numpy=
array([[-0.9089832 , -1.5041817 , -0.38031143],
       [ 0.89393514,  0.28413263,  1.4952382 ]], dtype=float32)>

In [14]:
tf.random.uniform(shape = (2,3), minval=0, maxval=10, dtype=tf.int32)

<tf.Tensor: id=30, shape=(2, 3), dtype=int32, numpy=
array([[8, 4, 9],
       [0, 8, 4]])>

### Declaring Variable

In [15]:
var0 = 24 # python Variable
var1 = tf.Variable(42) #rank 0 tensor
var2 = tf.Variable([[[0.,1.,2.], [3.,4.,5.],[6.,7.,8.], [9.,10.,11.]]]) # rank 3 Tensor

In [16]:
var0

24

In [17]:
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>

In [18]:
var2

<tf.Variable 'Variable:0' shape=(1, 4, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

TensorFlow will infer the datatype, defaulting to tf.float32 for float and tf.int32 for Integers

### The Datatype can be explicitly specified  

In [19]:
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64

### To reassign a value use var.assign()

In [20]:
var_reassign = tf.Variable(98.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [21]:
var_reassign.assign(89.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [22]:
initial_value = tf.random.normal(shape = (2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.0897177 , -0.06252133],
       [ 1.2819481 ,  1.7659457 ]], dtype=float32)>


We can assign "=" with assign(value), or assign_add(value) with "+=", or assign sub(value) with "-=".

### Shaping Tensor

In [23]:
tensor = tf.Variable([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
tensor.shape

TensorShape([2, 2, 3])

### Tensor Can be Reshaped and Retain the same value which is required for constructing neural network. 

In [24]:
tensor1 = tf.reshape(tensor, [2,6])# 2 Row and 6 Column
tensor1

<tf.Tensor: id=86, shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])>

In [25]:
tensor2 = tf.reshape(tensor, [1,12])# 1 Row and 12 column
tensor2

<tf.Tensor: id=89, shape=(1, 12), dtype=int32, numpy=array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])>

### Rank Of Tensor

The Rank Of Tensor is defined as the dimensions, which is number of indices which is required to specify any particular element of that tensor.

In [26]:
tf.rank(tensor)

<tf.Tensor: id=91, shape=(), dtype=int32, numpy=3>

The shape is () because the output here is scaler value.

### Specifying the element of tensor

In [27]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [28]:
tensor3 = tensor[0,1,1]# slice 0, row 0, and column 1
tensor3

<tf.Tensor: id=97, shape=(), dtype=int32, numpy=5>

In [29]:
print(tensor3.numpy())

5


### Casting a variable to Numpy variable

In [30]:
print(tensor.numpy())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
print(tensor3.numpy())

5


### Finding the size and length of the tensor

In [32]:
tensor_size = tf.size(input = tensor).numpy()
tensor_size

12

In [33]:
tensor_size.dtype

dtype('int32')

### Tensorflow Mathmatical Operation

can be used as numpy for artificial operation. Tensor flow can not execute these operation on the GPU or TPU.

In [34]:
a = tf.random.normal(shape = (2,2))
b = tf.random.normal(shape = (2,2))
c = a+b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[-0.5670554  -1.2005589 ]
 [-0.46201634 -0.03193014]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.51944333 -0.6488079 ]
 [ 0.3889383  -1.6224097 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.0864987  -1.8493668 ]
 [-0.07307804 -1.6543398 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.1804795 3.4201574]
 [0.0053404 2.7368402]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.33739573 0.15733676]
 [0.9295282  0.19121827]], shape=(2, 2), dtype=float32)


### Performing Element Wise Primitive Tensor Operation

In [35]:
tensor*tensor

<tf.Tensor: id=118, shape=(2, 2, 3), dtype=int32, numpy=
array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[ 49,  64,  81],
        [100, 121, 144]]])>

### Broadcasting In TesnorFlow

Element-Wise tensor operations support broadcasting in the same way that Numpy array do.

The Simplest Example is Multiplication of tensor by a scaler value.

In [36]:
tensor4 = tensor*4
print(tensor4)

tf.Tensor(
[[[ 4  8 12]
  [16 20 24]]

 [[28 32 36]
  [40 44 48]]], shape=(2, 2, 3), dtype=int32)


### Transpose Matrix Multiplication 

In [37]:
matrix_u = tf.constant([[6,7,6]])
matrix_v = tf.constant([[3,4,3]])
tf.matmul(matrix_u, tf.transpose(a = matrix_v))


<tf.Tensor: id=126, shape=(1, 1), dtype=int32, numpy=array([[64]])>

### Casting a tensor to another datatype

In [38]:
i = tf.cast(tensor, dtype=tf.int32)
i

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

### Casting with truncation 

In [39]:
j = tf.cast(tf.constant(4.9), dtype = tf.int32)
j

<tf.Tensor: id=129, shape=(), dtype=int32, numpy=4>

### Ragged Tensor

#### Below Example Shows how to declare a constant Ragged array

In [40]:
ragged = tf.ragged.constant([[5,6,7,8], [], [4,5,6], [6,7]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])

<tf.RaggedTensor [[5, 6, 7, 8], [], [4, 5, 6], [6, 7]]>
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


### Squared Difference of tensor

In [41]:
varx = [4,5,6,7]
vary = 8
varz = tf.math.squared_difference(varx, vary)
varz

<tf.Tensor: id=234, shape=(4,), dtype=int32, numpy=array([16,  9,  4,  1])>

### Calculate The Mean

Function Available tf.reduce_mean()

Similar to np.mean except that it infers the return datatype from the input tensor, wheares np.mean allow you to specify the output type.

tf.reduce_mean(input_tensor, axis = None, keepdims = None, name = None)

In [42]:
# Defining a constant
numbers = tf.constant([[8., 9.], [1.,2.]])

### Calculate The Mean Across All Axes

In [43]:
tf.reduce_mean(input_tensor = numbers)# Default axis = None

<tf.Tensor: id=237, shape=(), dtype=float32, numpy=5.0>

### Calculate The Mean Across Column (Reduce Row) With This:


In [44]:
tf.reduce_mean(input_tensor = numbers, axis = 0)

<tf.Tensor: id=239, shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

### When KeepDims = True 

In [45]:
tf.reduce_mean(input_tensor = numbers, axis = 0, keepdims=True)# The Reduce Axis is Retained with a length of 1

<tf.Tensor: id=241, shape=(1, 2), dtype=float32, numpy=array([[4.5, 5.5]], dtype=float32)>

### Calculate The Mean Across The Row (Reduce Column) With This:


In [46]:
numbers

<tf.Tensor: id=235, shape=(2, 2), dtype=float32, numpy=
array([[8., 9.],
       [1., 2.]], dtype=float32)>

In [47]:
tf.reduce_mean(input_tensor = numbers, axis = 1)

<tf.Tensor: id=243, shape=(2,), dtype=float32, numpy=array([8.5, 1.5], dtype=float32)>

### When Keepdims = True 

In [48]:
tf.reduce_mean(input_tensor = numbers, axis = 1, keepdims=True)

<tf.Tensor: id=245, shape=(2, 1), dtype=float32, numpy=
array([[8.5],
       [1.5]], dtype=float32)>

### Random Value Generation

#### tf.random.normal()

tf.random.normal() Output a tensor of the given shape filled with the value of the dtype type from the normal distribution

The Function is as Follow():

tf.random.normal(shape, mean = 0, stdev = 2, dtype = tf.float32, seed = None, name = None)

In [49]:
random_number = tf.random.normal(shape = (3,2), mean = 10, stddev=2)
print(random_number)

tf.Tensor(
[[ 6.5448337  8.585887 ]
 [ 8.236637   9.513138 ]
 [12.824016   9.403917 ]], shape=(3, 2), dtype=float32)


### tf.random.uniform()

The Function is This:

tf.random.uniform(shape, minval = 0, maxval = None, dtype = tf.float32, seed = None, name = None)

This Output a tensor of the given shape filled with the value of the uniform distribution in the range minval to maxval, where the lower bound is inclusive but the upper bound is not.

In [50]:
tf.random.uniform(shape = (3,3), minval = 0, maxval = None, seed = None, name = None)

<tf.Tensor: id=258, shape=(3, 3), dtype=float32, numpy=
array([[0.7620784 , 0.3422798 , 0.6051345 ],
       [0.96256995, 0.96575034, 0.55610645],
       [0.61223674, 0.04074502, 0.83708835]], dtype=float32)>

### Setting The Seed 

In [51]:
tf.random.set_seed(10)
random1 = tf.random.uniform(shape = (2,2), minval = 5, maxval = 10, dtype = tf.int32)
random2 = tf.random.uniform(shape = (3,3), minval = 5, maxval = 10, dtype = tf.int32)
print(random1)
print(random2)

tf.Tensor(
[[5 8]
 [6 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[8 5 9]
 [6 9 8]
 [7 9 9]], shape=(3, 3), dtype=int32)


In [52]:
tf.random.set_seed(10)
random1 = tf.random.uniform(shape = (2,2), minval = 5, maxval = 10, dtype = tf.int32)
random2 = tf.random.uniform(shape = (3,3), minval = 5, maxval = 10, dtype = tf.int32)
print(random1)
print(random2)

tf.Tensor(
[[5 8]
 [6 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[8 5 9]
 [6 9 8]
 [7 9 9]], shape=(3, 3), dtype=int32)


### Practical Example Of Random Values Using Dices 

In [53]:
dice11 = tf.Variable(tf.random.uniform([10,1], minval = 1, maxval = 7, dtype = tf.int32))
dice12 = tf.Variable(tf.random.uniform([10,1], minval = 1, maxval = 7, dtype = tf.int32))

# Let's Add
dice_sum = dice11+dice12
# We got three seperate (10*1) matrixs. To produce single 10x3 matrix, we'll concattenate them along dimesion 1.
final_matrix = tf.concat(values = [dice11, dice12, dice_sum], axis = 1)
print(final_matrix)

tf.Tensor(
[[ 2  2  4]
 [ 5  5 10]
 [ 3  5  8]
 [ 5  2  7]
 [ 1  6  7]
 [ 5  6 11]
 [ 5  4  9]
 [ 1  3  4]
 [ 5  2  7]
 [ 3  3  6]], shape=(10, 3), dtype=int32)


### Finding The indices of the largest and smalest element

The Following Function are available:

tf.argmax(input, axis = None, name = None, Output_type = tf.int64)

tf.argmin(input, axis = None, name = None, Output_type = tf.int64)

In [54]:
#1-d Tensor
tensor_1 = tf.constant([12,13,14,15,4,5,7,8])
print(tensor_1)

i = tf.argmax(input = tensor_1)
print('index of max: ', i)
print('Max Element: ', tensor_1[i].numpy())

i = tf.argmin(input = tensor_1)
print('index Of Min: ', i)
print('Min Element: ', tensor_1[i].numpy())


tf.Tensor([12 13 14 15  4  5  7  8], shape=(8,), dtype=int32)
index of max:  tf.Tensor(3, shape=(), dtype=int64)
Max Element:  15
index Of Min:  tf.Tensor(4, shape=(), dtype=int64)
Min Element:  4


### Saving and Restoring Using a checkpoint

In [55]:
variable_1 = tf.Variable([variable_1.assign([[0,0,0,0], [0,0,0,0]])])
checkpoint.restore(savepath)
print(variable_1)

NameError: name 'variable_1' is not defined

### Using tf.function()

tf.function is a function that will take a python function and return a tensorflow graph. The advatages of this is that graphs can apply optimization and exploit parallelism in the python function(func). tf.function is new in tensorflow 2.

### This Function is as follow:

tf.function(func = None, input_signature=None, autograph=True, experimental_autograph_options=None)

In [56]:
def f1(x,y):
    return tf.reduce_mean(input_tensor = tf)

### Calculate The Gradient

### Gradient Tape 

Another difference from numpy is that it can automatically track the gradient of any variable.

Open One Gradient Tape and Tape.Watch() track variable through

In [57]:
a = tf.random.normal(shape = (2,2))
b = tf.random.normal(shape = (2,2))
with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[ 0.7847288  -0.48479903]
 [ 0.9986899  -0.05840902]], shape=(2, 2), dtype=float32)


For all variable, the calculation is tracked by default and used to find the gradient, so do not use tape.watch()

In [58]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[ 0.7847288  -0.48479903]
 [ 0.9986899  -0.05840902]], shape=(2, 2), dtype=float32)


### You can gradient tape find higher-order derivatives by opening a few more.

In [62]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
        
    dcc_dca = outer_tape.gradient(dc_da,a)
    print(dcc_dca)

tf.Tensor(
[[1.7238906e-01 2.3412395e+00]
 [1.6570091e-03 8.1591243e-01]], shape=(2, 2), dtype=float32)
